### ISSUE TITLE
errors with DST

### ISSUE THREAD

**Issue by lulezi** [boombuler/recurrence#1]
Setting the `Recurrence.Location` parameter to a zone with DST will manipulate the time.

Example with `Recurrence.Frequence: Weekly`:
```
2017-03-20 15:00:00 +0100 CET
CET switches to DST => +0200 CEST
Recurrence.GetNextDate() returns
2017-03-27 16:00:00 +0200 CEST
```

If you'd like, I can commit some tests.

**Comment by boombuler** [comment]
Tests (for this) would be great!

**Comment by lulezi** [comment]
added tests, see https://github.com/boombuler/recurrence/pull/2

**Comment by boombuler** [comment]
Hi again,

this commit should fix the issues. Thanks for contributing. Hope this package is useful for you. Sorry for not providing any docs about this since it was only a spin-off from another project...

If you have anymore issues let me know
