### ISSUE TITLE
ndWeekly returning dat equal to d instead of the next dat

### ISSUE THREAD

**Issue by colinrieger** [boombuler/recurrence#4]
Passing a date into ndWeekly that matches the criteria was returning that date instead of the next date.

Issue seems to be with ndWeekly checking:
```
if dat.Before(d) {
    continue
}
```
instead of:
```
if !dat.After(d) {
    continue
}
```

Updated ndWeekly and tweaked weekly_test.go to attempt to fix this issue in #3.

**Comment by boombuler** [comment]
Fixed in a5ac9419d983f2589e4340bdcf1120a3cd0c2011
